# Generated by Django 2.2.1 on 2019-05-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Receive'), (2, 'Payment'), (3, 'Expense'), (4, 'Sale'), (5, 'Purchase'), (6, 'SaleDelivery'), (7, 'PurchaseDelivery')], default=1)),
                ('name', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=64)),
                ('no_start_from', models.IntegerField(blank=True, default=1000, null=True)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voucher_sub_type_credit_account', to='account.Account')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voucher_sub_type_debit_account', to='account.Account')),
            ],
        ),
    ]
