# Generated by Django 2.2.1 on 2019-05-16 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20190516_2352'),
        ('account', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=64)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Receive'), (2, 'Payment'), (3, 'Expense'), (4, 'Sale'), (5, 'Purchase'), (6, 'SaleDelivery'), (7, 'PurchaseDelivery')], default=1, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('accounts', models.ManyToManyField(blank=True, to='account.Account')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='party.Party')),
                ('ref_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='voucher.Voucher')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voucher.VoucherSubType')),
            ],
        ),
    ]
