# Generated by Django 2.2.4 on 2019-08-17 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20190815_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='entry_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
