# Generated by Django 2.2.4 on 2019-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20190817_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
