# Generated by Django 2.2.1 on 2019-05-16 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True)),
                ('currency', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('passport', models.CharField(blank=True, max_length=64, null=True)),
                ('etin', models.CharField(blank=True, max_length=64, null=True)),
                ('bin', models.CharField(blank=True, max_length=64, null=True)),
                ('vat_reg_no', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor')], default=2)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True)),
                ('currency', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('passport', models.CharField(blank=True, max_length=64, null=True)),
                ('etin', models.CharField(blank=True, max_length=64, null=True)),
                ('bin', models.CharField(blank=True, max_length=64, null=True)),
                ('vat_reg_no', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor')], default=1)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
