# Generated by Django 2.2.1 on 2019-05-16 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='etin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vat_reg_no',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='etin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vat_reg_no',
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True)),
                ('currency', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('passport', models.CharField(blank=True, max_length=64, null=True)),
                ('etin', models.CharField(blank=True, max_length=64, null=True)),
                ('bin', models.CharField(blank=True, max_length=64, null=True)),
                ('vat_reg_no', models.CharField(blank=True, max_length=64, null=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='party_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='party.Party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='party_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='party.Party'),
            preserve_default=False,
        ),
    ]
