# Generated by Django 2.2.4 on 2019-08-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_partysubtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='account_id',
            new_name='account',
        ),
    ]
