# Generated by Django 2.2.4 on 2019-08-12 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20190810_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
