# Generated by Django 2.2.3 on 2019-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='user name'),
        ),
    ]
